stages:
  prepare:
    cmd: python src/prepare.py --in data/raw/dataset.csv --out_dir data/processed
    deps:
      - src/prepare.py
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
      - data/processed/vectorizer.joblib
  train:
    cmd: python src/train.py --train data/processed/train.csv --model models/model.pkl --params params.yaml
    deps:
      - src/train.py
      - data/processed/train.csv
      - data/processed/vectorizer.joblib
      - params.yaml
    outs:
      - models/model.pkl

  eval:
    cmd: python src/eval.py --test data/processed/test.csv --model models/model.pkl --out metrics.json
    deps:
      - src/eval.py
      - data/processed/test.csv
      - models/model.pkl
    metrics:
      - metrics.json:
          cache: false
